file_read = open('Codingal123.txt','r')
print("File in Read Mode.")
print(file_read.read())
file_read.close()
file_write = open('Codingal123.txt','w')
file_write.write("File in Write Mode.")
file_write.write("Hi! I am penguin. I am 1 yr old.")
file_write.close()
file_append = open('Codingal123.txt','a')
file_append.write("\n File in append Mode....")
file_append.write("Hi! I am penguin. I am 1 yr old.")
file_append.close()